### ISSUE TITLE
Functiontests for all components

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/etos#3]
### Description

Create function tests for all components and the ETOS system.

- [ ] eiffel-community/etos-test-runner#3
- [ ] eiffel-community/etos-environment-provider#3
- [ ] eiffel-community/etos-api#3
- [ ] eiffel-community/etos-suite-starter#3
- [ ] eiffel-community/etos-library#3
- [ ] eiffel-community/etos-client#4
- [ ] eiffel-community/etos-suite-runner#3

### Motivation

Keep the project safe from developer mistakes.

### Exemplification

Would be a great ETOS suite for testing your deployment and would also keep the project safe.

### Benefits

Tests are good.

### Possible Drawbacks

None
